import './globals.css'
import { Play } from 'next/font/google'
import { Inter } from 'next/font/google'
import { Overpass_Mono } from 'next/font/google'
import Navbar from '@/components/Navbar'

const play = Play({
  weight: ['400', '700'],
  variable: '--sec-font',
  subsets: ['latin'],
})

const overpassMono = Overpass_Mono({
  variable: '--sec-font',
  subsets: ['latin'],
})

const inter = Inter({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--body-font',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${overpassMono.variable} scroll-smooth`}
    >
      <body className="font-body">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
